"""initial schema int album ids

Revision ID: 4b9d9fdb7c22
Revises: 
Create Date: 2026-10-03 16:49:52.637164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4b9d9fdb7c22'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('genre', sa.String(length=255), nullable=False),
    sa.Column('music_count', sa.Integer(), nullable=False),
    sa.Column('releaseDate', sa.Date(), nullable=False),
    sa.Column('llm_description', sa.String(length=500), nullable=False),
    sa.Column('llm_emotion_analysis', sa.String(length=255), nullable=False),
    sa.Column('llm_overall_public_reception', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('musics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('genre', sa.String(length=255), nullable=False),
    sa.Column('llm_description', sa.String(length=500), nullable=False),
    sa.Column('llm_emotion_analysis', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('music_id', sa.Integer(), nullable=True),
    sa.Column('rater_name', sa.String(length=255), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_generated', sa.Boolean(), nullable=False),
    sa.CheckConstraint('(album_id IS NOT NULL AND music_id IS NULL) OR (album_id IS NULL AND music_id IS NOT NULL)', name='ck_rate_target'),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['music_id'], ['musics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rates')
    op.drop_table('musics')
    op.drop_table('albums')
    # ### end Alembic commands ###